// combine/mx-solidjs-template-dapp-1f72f15953655916ac9817b65307661f2de15950/src/pages/Dashboard/widgets/SignMessage/SignMessage.tsx
import {
  faFileSignature,
  faBroom,
  faArrowsRotate
} from '@fortawesome/free-solid-svg-icons';
import { Address, Message } from '@terradharitri/sdk-core';
import Fa from 'solid-fa';
import { createSignal } from 'solid-js';
import { Button } from 'components/Button';
import { OutputContainer } from 'components/OutputContainer/OutputContainer';
import { getAccount, getAccountProvider } from 'lib';
import { SignFailure, SignSuccess } from './components';

export const SignMessage = () => {
  const [message, setMessage] = createSignal('');
  const [signedMessage, setSignedMessage] = createSignal<Message | null>(null);
  const [state, setState] = createSignal<'pending' | 'success' | 'error'>(
    'pending'
  );
  const [signatrue, setSignatrue] = createSignal('');
  const address = getAccount()?.address;
  const provider = getAccountProvider();

  const handleSubmit = async () => {
    try {
      const messageToSign = new Message({
        address: new Address(address),
        data: Buffer.from(message())
      });
      const signedMessageResult = await provider.signMessage(messageToSign);

      if (!signedMessageResult?.signature) {
        setState('error');
        return;
      }

      setState('success');
      setSignatrue(Buffer.from(signedMessageResult?.signature).toString('hex'));
      setSignedMessage(signedMessageResult);
      setMessage('');
    } catch (error) {
      console.error(error);
      setState('error');
    }
  };

  const handleClear = (e: MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setSignatrue('');
    setState('pending');
  };

  return (
    <div class='flex flex-col gap-6'>
      <div class='flex gap-2 items-start'>
        {['success', 'error'].includes(state()) ? (
          <Button
            data-testid='closeTransactionSuccessBtn'
            id='closeButton'
            onClick={handleClear}
          >
            <>
              <Fa
                icon={state() === 'success' ? faBroom : faArrowsRotate}
                class='mr-1'
              />
              {state() === 'error' ? 'Try again' : 'Clear'}
            </>
          </Button>
        ) : (
          <Button data-testid='signMsgBtn' onClick={handleSubmit}>
            <>
              <Fa icon={faFileSignature} class='mr-1' />
              Sign
            </>
          </Button>
        )}
      </div>
      <OutputContainer>
        {!['success', 'error'].includes(state()) && (
          <textarea
            placeholder='Write message here1'
            class='resize-none w-full h-32 rounded-lg focus:outline-none focus:border-blue-500'
            onChange={(event) => {
              setMessage(event.currentTarget.value);
            }}
            onKeyUp={(event) => {
              setMessage(event.currentTarget.value);
            }}
          />
        )}

        {state() === 'success' && signedMessage() != null && (
          <SignSuccess
            signedMessage={signedMessage()}
            signature={signatrue()}
          />
        )}

        {state() === 'error' && <SignFailure />}
      </OutputContainer>
    </div>
  );
};

// combine/mx-template-dapp-angular/mx-template-dapp-angular-09f9521c453a2f9b79aa479668ce0d8563c97cce/src/app/widgets/sign-message/sign-message.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import {
  faPen,
  faBroom,
  faRotateRight,
} from '@fortawesome/free-solid-svg-icons';
import { OutputContainerComponent } from '../../components/output-container/output-container.component';
import { LabelComponent } from '../../components/label/label.component';
import { ButtonComponent } from '../../components/button/button.component';
import { getAccount } from '@terradharitri/sdk-dapp/out/methods/account/getAccount';
import { getAccountProvider } from '@terradharitri/sdk-dapp/out/providers/helpers/accountProvider';
import { Message } from '@terradharitri/sdk-core/out';

@Component({
  selector: 'app-sign-message',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    FontAwesomeModule,
    OutputContainerComponent,
    LabelComponent,
    ButtonComponent,
  ],
  templateUrl: './sign-message.component.html',
  styleUrls: ['./sign-message.component.css'],
})
export class SignMessageComponent {
  message: string = '';
  signedMessage: any = null;
  state: 'pending' | 'success' | 'error' = 'pending';
  signature: string = '';
  address: string = '';

  // FontAwesome icons
  faPen = faPen;
  faBroom = faBroom;
  faRotateRight = faRotateRight;

  async handleSubmit() {
    try {
      // Get the account data from the store
      const account = getAccount();
      this.address = account.address || '';

      if (!this.address) {
        console.error('No account address found');
        this.state = 'error';
        return;
      }

      console.log('Signing message:', this.message);

      // Create a Message object from the message
      const messageToSign = new Message({
        data: Buffer.from(this.message, 'utf8'),
      });

      // Get the account provider and sign the message
      const provider = getAccountProvider();
      const signedMessage = await provider.signMessage(messageToSign);

      if (!signedMessage) {
        console.error('No signed message found');
        this.state = 'error';
        return;
      }

      // Extract the signature from the signed message
      this.signature = signedMessage.signature
        ? Buffer.from(signedMessage.signature).toString('hex')
        : '';
      this.state = 'success';
      this.signedMessage = signedMessage;
      this.message = '';
    } catch (error) {
      console.error('Error signing message:', error);
      this.state = 'error';
    }
  }

  handleClear(event: MouseEvent) {
    event.preventDefault();
    event.stopPropagation();
    this.signature = '';
    this.signedMessage = null;
    this.state = 'pending';
    this.message = '';
  }

  get encodedMessage(): string {
    if (!this.signedMessage) return '';
    return (
      '0x' +
      Array.from(this.signedMessage.data, (byte: number) =>
        byte.toString(16).padStart(2, '0')
      ).join('')
    );
  }

  get decodedMessage(): string {
    if (!this.signedMessage) return '';
    return new TextDecoder().decode(this.signedMessage.data);
  }
}
