// combine/mx-sdk-template-dapp/mx-solidjs-template-dapp-1f72f15953655916ac9817b65307661f2de15950/src/lib/sdkDapp/components/TransactionsTable/TransactionsTable.tsx
import { createEffect, createMemo } from 'solid-js';
import { useStore } from 'hooks';
import {
  TransactionsTableController,
  networkSelector,
  accountSelector,
  ServerTransactionType
} from 'lib';
import {
  ITransactionsTableRow,
  TransactionsTableSDKPropsType
} from 'lib/sdkDappUI/sdkDappUI.types';
import { IPropsWithClass } from 'types';

interface TransactionsTablePropsType extends IPropsWithClass {
  transactions?: ServerTransactionType[];
}

export const TransactionsTable = (props: TransactionsTablePropsType) => {
  let elementRef: Partial<TransactionsTableSDKPropsType> | undefined;

  const store = useStore();
  const network = createMemo(() => networkSelector(store()));
  const account = createMemo(() => accountSelector(store()));

  createEffect(async () => {
    if (!elementRef) {
      return;
    }

    const data = await TransactionsTableController.processTransactions({
      address: account().address,
      rewaLabel: network().rewaLabel,
      explorerAddress: network().explorerAddress,
      transactions: props.transactions || []
    });

    Object.assign(elementRef, props, {
      transactions: data as ITransactionsTableRow[]
    });
  });

  return <mvx-transactions-table ref={elementRef} />;
};

// combine/mx-template-dapp-nextjs-3eff487591b32eafb6656d424dca2f71e5cd15a0/src/components/TransactionsTable/TransactionsTable.tsx
'use client';
import { useEffect, useState } from 'react';
import {
  ITransactionsTableRow,
  MvxTransactionsTable,
  ServerTransactionType,
  TransactionsTableController,
  useGetAccount,
  useGetNetworkConfig
} from '@/lib';

interface TransactionsTablePropsType {
  transactions?: ServerTransactionType[];
}

export const TransactionsTable = ({
  transactions = []
}: TransactionsTablePropsType) => {
  const { address } = useGetAccount();
  const { network } = useGetNetworkConfig();
  const [processedTransactions, setProcessedTransactions] = useState<
    ITransactionsTableRow[]
  >([]);

  useEffect(() => {
    processTransactions();
  }, []);

  const processTransactions = async () => {
    const transactionsData =
      await TransactionsTableController.processTransactions({
        address,
        rewaLabel: network.rewaLabel,
        explorerAddress: network.explorerAddress,
        transactions
      });

    setProcessedTransactions(
      transactionsData as unknown as ITransactionsTableRow[]
    );
  };

  return <MvxTransactionsTable transactions={processedTransactions} />;
};
