// combine/mx-template-dapp-angular/mx-template-dapp-angular-09f9521c453a2f9b79aa479668ce0d8563c97cce/src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { AuthService } from '../../services/auth.service';
import { EnvironmentService } from '../../services/environment.service';
import { RouteNamesEnum } from '../../route-names.enum';
import { ButtonComponent } from '../button/button.component';
import { MxLinkComponent } from '../drt-link/drt-link.component';
import { NotificationsButtonComponent } from '../notifications-button/notifications-button.component';
import { ConnectButtonComponent } from '../connect-button/connect-button.component';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, ButtonComponent, MxLinkComponent, NotificationsButtonComponent, ConnectButtonComponent],
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent {
  routeNames = RouteNamesEnum;

  constructor(
    private authService: AuthService,
    private environmentService: EnvironmentService,
    private router: Router
  ) {}

  get isLoggedIn(): boolean {
    return this.authService.getIsLoggedIn();
  }

  get environment(): string {
    return this.environmentService.environment;
  }

  async handleLogout() {
    await this.authService.logout();
    this.router.navigate([RouteNamesEnum.home]);
  }
} 
<header class="flex flex-row align-center justify-between pl-6 pr-6 pt-6">
  <app-drt-link
    [className]="'flex items-center justify-between'"
    [to]="isLoggedIn ? routeNames.dashboard : routeNames.home"
  >
    <!-- DharitrILogo equivalent - you can replace with actual SVG -->
    <div class="w-full h-6">DharitrI</div>
  </app-drt-link>

  <nav class="h-full w-full text-sm sm:relative sm:left-auto sm:top-auto sm:flex sm:w-auto sm:flex-row sm:justify-end sm:bg-transparent">
    <div class="flex justify-end container drt-auto items-center gap-2">
      <div class="flex gap-1 items-center">
        <div class="w-2 h-2 rounded-full bg-green-500"></div>
        <p class="text-gray-600">{{ environment }}</p>
      </div>

      <ng-container *ngIf="isLoggedIn">
        <app-notifications-button></app-notifications-button>
        <app-button
          (onClick)="handleLogout()"
          [className]="'inline-block rounded-lg px-3 py-2 text-center hover:no-underline my-0 text-gray-600 hover:bg-slate-100 drt-0'"
        >
          Close
        </app-button>
      </ng-container>

      <app-connect-button *ngIf="!isLoggedIn">
        Connect
      </app-connect-button>
    </div>
  </nav>
</header>

// combine/mx-lite-wallet-dapp/mx-lite-wallet-dapp-a2a37fa9ed96fb607ee805c3cf310ed4a7f5fab0/src/components/Layout/Header/Header.tsx
import { useMatch } from 'react-router-dom';
import { MxLink } from 'components/MxLink';
import { useGetIsLoggedIn } from 'lib';
import { DataTestIdsEnum, RouteNamesEnum } from 'localConstants';
import { routeNames } from 'routes';
import DharitrILogo from '../../../assets/img/dharitri-logo.svg?react';
import { NetworkSwitcher } from '../../NetworkSwitcher';

export const Header = () => {
  const isLoggedIn = useGetIsLoggedIn();
  const isUnlockRoute = Boolean(useMatch(RouteNamesEnum.unlock));

  const ConnectButton = isUnlockRoute ? null : (
    <MxLink data-testid={DataTestIdsEnum.connectBtn} to={RouteNamesEnum.unlock}>
      Connect
    </MxLink>
  );

  return (
    <header className='flex flex-row align-center justify-between pl-6 pr-6 pt-6'>
      <MxLink
        className='flex items-center justify-between'
        to={isLoggedIn ? routeNames.dashboard : routeNames.home}
      >
        <DharitrILogo className='w-full h-6' />
      </MxLink>

      <nav className='h-full w-full text-sm sm:relative sm:left-auto sm:top-auto sm:flex sm:w-auto sm:flex-row sm:justify-end sm:bg-transparent'>
        <div className='flex justify-end container mx-auto items-center gap-2'>
          <NetworkSwitcher />

          {isLoggedIn ? (
            <MxLink
              className='inline-block rounded-lg px-3 py-2 text-center hover:no-underline my-0 text-gray-600 hover:bg-slate-100 mx-0'
              data-testid={DataTestIdsEnum.logoutBtn}
              to={routeNames.logout}
            >
              Close
            </MxLink>
          ) : (
            ConnectButton
          )}
        </div>
      </nav>
    </header>
  );
};
