// combine/mx-solidjs-template-dapp-1f72f15953655916ac9817b65307661f2de15950/src/pages/Dashboard/widgets/Account/Account.tsx
import { createMemo, Show } from 'solid-js';
import { Label } from 'components/Label';
import { OutputContainer } from 'components/OutputContainer/OutputContainer';
import { useStore } from 'hooks';
import { getAccount, networkSelector } from 'lib';
import { FormatAmount } from 'lib/sdkDapp/components/FormatAmount/FormatAmount';
import { Username } from './components';

export const Account = () => {
  const store = useStore();
  const network = createMemo(() => networkSelector(store()));
  const account = createMemo(() => getAccount(store()));

  return (
    <OutputContainer>
      <div class='flex flex-col text-black' data-testid='topInfo'>
        <Show when={store()}>
          <p class='truncate'>
            <Label>Address: </Label>
            <span data-testid='accountAddress'>{account().address}</span>
          </p>

          <Username account={account()} />
          <p>
            <Label>Shard: </Label> {account().shard}
          </p>

          <p>
            <Label>Balance: </Label>
            <FormatAmount
              value={account().balance}
              rewaLabel={network().rewaLabel}
              data-testid='balance'
            />
          </p>
        </Show>
      </div>
    </OutputContainer>
  );
};

// combine/mx-template-dapp-nextjs/mx-template-dapp-nextjs-3eff487591b32eafb6656d424dca2f71e5cd15a0/src/app/dashboard/widgets/Account/Account.tsx
'use client';
import { OutputContainer, Label } from '@/components';
import {
  useGetAccountInfo,
  useGetNetworkConfig,
  MvxFormatAmount,
  FormatAmountController,
  DIGITS,
  DECIMALS
} from '@/lib';
import { Username } from './components';

export const Account = () => {
  const { address, account } = useGetAccountInfo();
  const { network } = useGetNetworkConfig();

  const { isValid, valueDecimal, valueInteger, label } =
    FormatAmountController.getData({
      digits: DIGITS,
      decimals: DECIMALS,
      rewaLabel: network.rewaLabel,
      input: account.balance
    });

  return (
    <OutputContainer>
      <div className='flex flex-col text-black' data-testid='topInfo'>
        <p className='truncate'>
          <Label>Address: </Label>
          <span data-testid='accountAddress'> {address}</span>
        </p>

        <Username account={account} />

        <p>
          <Label>Shard: </Label>
          {account.shard}
        </p>

        <p>
          <Label>Balance: </Label>
          <MvxFormatAmount
            isValid={isValid}
            valueInteger={valueInteger}
            valueDecimal={valueDecimal}
            label={label}
            data-testid='balance'
          />
        </p>
      </div>
    </OutputContainer>
  );
};
